### ISSUE TITLE
`forEach` for `HTMLCollection`

### ISSUE THREAD

**Issue by AlexWayfer** [brettdewoody/polyfill-nodelist-foreach#2]
```javascript
typeof someElement.children // HTMLCollection
someElement.children.forEach( /* ... */);
```

**Comment by brettdewoody** [comment]
@AlexWayfer Can you explain? Is this a issue, question, comment?

**Comment by AlexWayfer** [comment]
@brettdewoody, of course, sorry. It's a feature request. But I resolved this problem via `childNodes` instead of `children`. So, you can just close this issue without changes, if you want, or add `forEach` also for `HTMLCollection`. But… it will contradict the name of the project. So, I'll close this issue :)

**Comment by brettdewoody** [comment]
@AlexWayfer Do you know the browser support for `forEach` on `HTMLCollection`?

**Comment by AlexWayfer** [comment]
> @AlexWayfer Do you know the browser support for forEach on HTMLCollection?

No :disappointed:
